### ISSUE TITLE
api endpoint already in use, ways to change it

### ISSUE THREAD

**Issue by SmikeSix2** [yangbo/swagger-grails4#31]
hi our grails 4 uses /api with url rewrites, its there a way to have a hidden api endpoint for swagger? couldnt see any configs about it

**Comment by yangbo** [comment]
hi SmikeSix, there is no config for '/api' url of swagger, you have to can change it in the 'UrlMappings.groovy' source file, good luck : )

![image](https://github.com/yangbo/swagger-grails4/assets/23898/0c3496db-e7ea-4b49-82dd-08383c79178f)
